// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Modelos;

public partial class Account_history
{
    public int id_history { get; set; }

    public int account_id { get; set; }

    public virtual Account account { get; set; }

    public virtual ICollection<history_object> history_object { get; set; } = new List<history_object>();
}