// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Modelos;

public partial class Account
{
    public int id { get; set; }

    public string password { get; set; }

    public string email { get; set; }

    public string role { get; set; }

    public sbyte active { get; set; }

    public virtual ICollection<Account_Balance> Account_Balance { get; set; } = new List<Account_Balance>();

    public virtual ICollection<Company> Company { get; set; } = new List<Company>();

    public virtual ICollection<User> User { get; set; } = new List<User>();
}