// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Modelos;

public partial class Account_Balance
{
    public int balance_id { get; set; }

    public int balance { get; set; }

    public int max_balance { get; set; }

    public long account_id { get; set; }

    public virtual Account account { get; set; }
}