// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Model.Modelos.Configurations;
using System;
using System.Collections.Generic;
#nullable disable

namespace Model.Modelos;

public partial class BancaDBContext : DbContext
{
    public BancaDBContext(DbContextOptions<BancaDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cuenta> Cuenta { get; set; }

    public virtual DbSet<Empresa> Empresa { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8_general_ci")
            .HasCharSet("utf8");

        modelBuilder.ApplyConfiguration(new Configurations.CuentaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EmpresaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsuarioConfiguration());
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
