// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Modelos;

public partial class Company
{
    public string cuit { get; set; }

    public long account_id { get; set; }

    public string phone { get; set; }

    public string address { get; set; }

    public string name { get; set; }

    public string surname { get; set; }

    public virtual Account account { get; set; }
}