// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Modelos;

public partial class Empresa
{
    public string Cuit { get; set; }

    public int IdCuenta { get; set; }

    public virtual Cuenta IdCuentaNavigation { get; set; }
}