// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Modelos;

public partial class Usuario
{
    public string Dni { get; set; }

    public int IdCuenta { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Tel { get; set; }

    public virtual Cuenta IdCuentaNavigation { get; set; }
}