// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Modelos;

public partial class History_object_DTO
{
    public int account_id { get; set; }

    public string type { get; set; }

    public int value { get; set; }

    public DateTime Date { get; set; }

    public int? other_account_id { get; set; }

}