// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Modelos;
using System;
using System.Collections.Generic;

namespace Model.Modelos.Configurations
{
    public partial class Account_historyConfiguration : IEntityTypeConfiguration<Account_history>
    {
        public void Configure(EntityTypeBuilder<Account_history> entity)
        {
            entity.HasKey(e => e.id_history).HasName("PRIMARY");

            entity.HasIndex(e => e.account_id, "account_id_idx");

            entity.HasOne(d => d.account).WithMany(p => p.Account_history)
                .HasForeignKey(d => d.account_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("account_history");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Account_history> entity);
    }
}
