// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Modelos;
using System;
using System.Collections.Generic;

namespace Model.Modelos.Configurations
{
    public partial class Account_BalanceConfiguration : IEntityTypeConfiguration<Account_Balance>
    {
        public void Configure(EntityTypeBuilder<Account_Balance> entity)
        {
            entity.HasKey(e => e.balance_id).HasName("PRIMARY");

            entity.HasIndex(e => e.account_id, "Balance_Account_idx");

            entity.HasOne(d => d.account).WithMany(p => p.Account_Balance)
                .HasForeignKey(d => d.account_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Balance_Account");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Account_Balance> entity);
    }
}
