// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Modelos;
using System;
using System.Collections.Generic;

namespace Model.Modelos.Configurations
{
    public partial class CompanyConfiguration : IEntityTypeConfiguration<Company>
    {
        public void Configure(EntityTypeBuilder<Company> entity)
        {
            entity.HasKey(e => e.cuit).HasName("PRIMARY");

            entity
                .HasCharSet("utf8mb4")
                .UseCollation("utf8mb4_0900_ai_ci");

            entity.HasIndex(e => e.account_id, "Company_to_account_idx");

            entity.Property(e => e.cuit).HasMaxLength(250);
            entity.Property(e => e.address)
                .IsRequired()
                .HasMaxLength(45);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(45);
            entity.Property(e => e.phone)
                .IsRequired()
                .HasMaxLength(45);
            entity.Property(e => e.surname)
                .IsRequired()
                .HasMaxLength(45);

            entity.HasOne(d => d.account).WithMany(p => p.Company)
                .HasForeignKey(d => d.account_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Company_to_account");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Company> entity);
    }
}
