// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Modelos;
using System;
using System.Collections.Generic;

namespace Model.Modelos.Configurations
{
    public partial class ContactsConfiguration : IEntityTypeConfiguration<Contacts>
    {
        public void Configure(EntityTypeBuilder<Contacts> entity)
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.HasIndex(e => e.ContactAccountId, "ContactAccountId");

            entity.HasIndex(e => e.UserId, "UserId");

            entity.HasOne(d => d.ContactAccount).WithMany(p => p.ContactsContactAccount)
                .HasForeignKey(d => d.ContactAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Contacts_ibfk_2");

            entity.HasOne(d => d.User).WithMany(p => p.ContactsUser)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Contacts_ibfk_1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Contacts> entity);
    }
}
