// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Modelos;
using System;
using System.Collections.Generic;

namespace Model.Modelos.Configurations
{
    public partial class EmpresaConfiguration : IEntityTypeConfiguration<Empresa>
    {
        public void Configure(EntityTypeBuilder<Empresa> entity)
        {
            entity.HasKey(e => e.Cuit).HasName("PRIMARY");

            entity.ToTable("empresa");

            entity.HasIndex(e => e.IdCuenta, "id_idx");

            entity.Property(e => e.Cuit)
                .ValueGeneratedNever()
                .HasColumnName("cuit");
            entity.Property(e => e.IdCuenta).HasColumnName("id_cuenta");

            entity.HasOne(d => d.IdCuentaNavigation).WithMany(p => p.Empresa)
                .HasForeignKey(d => d.IdCuenta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("cuenta_a_empresa");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Empresa> entity);
    }
}
