// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Modelos;
using System;
using System.Collections.Generic;

namespace Model.Modelos.Configurations
{
    public partial class history_objectConfiguration : IEntityTypeConfiguration<history_object>
    {
        public void Configure(EntityTypeBuilder<history_object> entity)
        {
            entity.HasKey(e => e.history_obj_id).HasName("PRIMARY");

            entity.HasIndex(e => e.account_history_id, "history_object_to_history_idx");

            entity.Property(e => e.type)
                .IsRequired()
                .HasMaxLength(45);

            entity.HasOne(d => d.account_history).WithMany(p => p.history_object)
                .HasForeignKey(d => d.account_history_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("history_object_to_history");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<history_object> entity);
    }
}
