// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Modelos;
using System;
using System.Collections.Generic;

namespace Model.Modelos.Configurations
{
    public partial class History_objectConfiguration : IEntityTypeConfiguration<History_object>
    {
        public void Configure(EntityTypeBuilder<History_object> entity)
        {
            entity.HasKey(e => e.history_obj_id).HasName("PRIMARY");

            entity.HasIndex(e => e.account_id, "History_Account_idx");

            entity.HasIndex(e => e.other_account_id, "History_Other_Account_idx");

            entity.Property(e => e.date).HasColumnType("datetime");
            entity.Property(e => e.type)
                .IsRequired()
                .HasMaxLength(45);

            entity.HasOne(d => d.account).WithMany(p => p.History_objectaccount)
                .HasForeignKey(d => d.account_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("History_Account");

            entity.HasOne(d => d.other_account).WithMany(p => p.History_objectother_account)
                .HasForeignKey(d => d.other_account_id)
                .HasConstraintName("History_Other_Account");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<History_object> entity);
    }
}
