// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Modelos;
using System;
using System.Collections.Generic;

namespace Model.Modelos.Configurations
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.HasKey(e => e.dni).HasName("PRIMARY");

            entity
                .HasCharSet("utf8mb4")
                .UseCollation("utf8mb4_0900_ai_ci");

            entity.HasIndex(e => e.account_id, "usuario_a_cuenta_idx");

            entity.Property(e => e.dni).HasMaxLength(50);
            entity.Property(e => e.address).HasMaxLength(45);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(45);
            entity.Property(e => e.phone)
                .IsRequired()
                .HasMaxLength(45);
            entity.Property(e => e.surname)
                .IsRequired()
                .HasMaxLength(45);

            entity.HasOne(d => d.account).WithMany(p => p.User)
                .HasForeignKey(d => d.account_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("usuario_a_cuenta");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<User> entity);
    }
}
